### ISSUE TITLE
Add notebook example?

### ISSUE THREAD

**Issue by ian-whitestone** [intake/intake-avro#8]
The README references a notebook in the examples directory, but I'm not able to see anything (checked both branches).

Would it be possible to add this? Would love to play around with the package.

**Comment by ian-whitestone** [comment]
Or maybe just update the readme to reference the [`quickstart.rst`](https://github.com/ContinuumIO/intake-avro/blob/master/docs/source/quickstart.rst) if that should be used instead?

**Comment by martindurant** [comment]
Yes, you are right that it would be worthwhile including an example notebook. Here is a shortened example:

Assuming intake and intake-avro have been installed (`conda install -c intake intake-avro`), if you want to use bags, you will also need `fastavro`, and of course `dask.bag`. Here demonstrated with the test data included in this repo.

```
>>> input intake
>>> s = intake.open_avro_sequence('*.avro')  # a data source
>>> b = s.to_dask()  # a dask.bag
>>> b.npartitions   # one part per file
2
>>> b.compute()
[{'username': 'miguno',
...
>>> s = intake.open_avro_sequence('https://github.com/miguno/avro-cli-examples/raw/master/twitter.avro')   # with remote version of the same
>>> s.read()   # directly to list of dicts
```

Note that the URL can be local files, gcs, s3, http remote files and can include glob characters. Each remote data storage backend has further requirements (gcsfs, s3fs, requests...) and may need `storage_options=` kwargs. It's not really possible to describe all of that in one place.

Note that you get one partition per file here. If you wanter intra-file partitioning, you would have to go directly to `uavro.dask_read_avro()` (only for strictly tabular data).

**Comment by martindurant** [comment]
@ian-whitestone , do you happen to have a reasonably-sized and interesting set of avro files on s3 that could be used in an example?

**Comment by ian-whitestone** [comment]
Not readily available, I work for a bank so can't exactly open it up :) . I can get some fake data up this weekend in my personal AWS account.

For some context, we have a data lake full of avro files. You can easily read this into a dataframe with spark, but I'm hoping to see if you can easily do this with dask.

**Comment by martindurant** [comment]
Appreciated.
I'll ask the Dask team whether there is appetite for read_avro/to_avro on dask.bag or/and dask.dataframe. The trouble is, there are potentially very many file types that could be considered here, and it's not obvious that extra code should be put into dask main for each. That was a (small) part of the reason for the Intake effort.

**Comment by ian-whitestone** [comment]
Yeah totally understand - hard to satisfy everyones needs. But at the same time, as a file format becomes popular enough, may make sense to add those into the dask library. Not sure where avro is in that journey...

**Comment by martindurant** [comment]
After talking with the team, I will indeed be adding a read_avro method to dask.bag, and probably also to dask.dataframe.

**Comment by martindurant** [comment]
https://github.com/ContinuumIO/intake-avro/issues/8

**Comment by martindurant** [comment]
https://github.com/dask/dask/pull/4000
